#!/usr/bin/env python3
"""
KemetCore tracking-doc generator.

Reads tools/manifest.py and (re)writes:
  - PROGRESS.md                                  (root master roadmap + mapping)
  - projects/<key>/STEPS.md                      (ordered build steps)
  - projects/<key>/CHECKPOINTS.md                (checkpoint table)
  - projects/<key>/TESTS.md                      (test plan + status)

Run after changing status in the manifest:  python tools/gen_tracking.py
Idempotent. Safe to run anytime. No external dependencies.
"""
import os
from datetime import date

import manifest as M

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SYM = M.SYMBOL


def w(path, text):
    full = os.path.join(ROOT, path)
    os.makedirs(os.path.dirname(full), exist_ok=True)
    with open(full, "w") as f:
        f.write(text)
    return path


def phase_cells(p):
    return " | ".join(SYM[p["phase"][i]] for i in range(6))


def project_progress_pct(p):
    done = sum(1 for i in range(6) if p["phase"][i] == "done")
    return int(done / 6 * 100)


def overall_pct():
    total = len(M.PROJECTS) * 6
    done = sum(1 for p in M.PROJECTS for i in range(6) if p["phase"][i] == "done")
    return int(done / total * 100), done, total


# --------------------------------------------------------------------------- #
# Per-project docs
# --------------------------------------------------------------------------- #
def gen_steps(p):
    lines = [f"# {p['name']} — Build STEPS",
             "",
             f"> Deity: {p['deity']} · Domain: {p['domain']} · Spec: [{p['doc']}](../../{p['doc']})",
             "",
             "_Auto-generated from `tools/manifest.py` — do not edit by hand; "
             "edit the manifest and run `python tools/gen_tracking.py`._",
             "",
             f"**Scope (current):** {p['scope']}",
             "",
             "## Ordered steps (6-phase lifecycle)",
             "",
             "| # | Phase | Step | Status |",
             "|:-:|:-----:|------|:------:|"]
    for i, (ph, desc) in enumerate(M.STD_STEPS, 1):
        st = p["phase"][ph]
        lines.append(f"| {i} | P{ph} | {desc} | {SYM[st]} |")
    deps = ", ".join(f"[{d}](../{d}/STEPS.md)" for d in p["depends"]) or "none"
    lines += ["",
              f"**Depends on:** {deps}",
              "",
              "## How to resume this project",
              "",
              "```bash",
              f"# 1. run its tests (Phase 0/1 must stay green)",
              f"pytest projects/{p['key']}/tests -v",
              f"# 2. read its checkpoints + tests",
              f"cat projects/{p['key']}/CHECKPOINTS.md projects/{p['key']}/TESTS.md",
              f"# 3. continue from the first ⬜ step above (next phase = RTL)",
              "```",
              ""]
    return "\n".join(lines)


def gen_checkpoints(p):
    lines = [f"# {p['name']} — CHECKPOINTS",
             "",
             "_Auto-generated from `tools/manifest.py`._",
             "",
             "| ID | Phase | Checkpoint | Status |",
             "|----|:-----:|------------|:------:|"]
    for cid, desc, ph, st in p["checkpoints"]:
        lines.append(f"| {cid} | P{ph} | {desc} | {SYM[st]} |")
    done = sum(1 for c in p["checkpoints"] if c[3] == "done")
    lines += ["",
              f"**Progress:** {done}/{len(p['checkpoints'])} checkpoints complete "
              f"({project_progress_pct(p)}% of phases).",
              ""]
    return "\n".join(lines)


def gen_tests(p):
    lines = [f"# {p['name']} — TESTS",
             "",
             "_Auto-generated from `tools/manifest.py`._",
             "",
             f"Run: `pytest projects/{p['key']}/tests -v`",
             "",
             "| Test | Verifies | Status |",
             "|------|----------|:------:|"]
    for name, what, st in p["tests"]:
        mark = "✅" if st == "pass" else ("🔧" if st == "partial" else "⬜")
        lines.append(f"| `{name}` | {what} | {mark} |")
    npass = sum(1 for t in p["tests"] if t[2] == "pass")
    lines += ["",
              f"**{npass}/{len(p['tests'])} tests passing.**",
              ""]
    return "\n".join(lines)


# --------------------------------------------------------------------------- #
# Root PROGRESS.md
# --------------------------------------------------------------------------- #
def gen_progress():
    pct, done, total = overall_pct()
    bar_len = 30
    filled = int(bar_len * pct / 100)
    bar = "█" * filled + "░" * (bar_len - filled)
    lines = [
        "# 𓂀 KemetCore — Master PROGRESS & Mapping",
        "",
        f"_Auto-generated by `tools/gen_tracking.py` on {date.today().isoformat()}. "
        "Single source of truth: `tools/manifest.py`._",
        "",
        "> **Resume this session in 30 seconds:** read this file top-to-bottom, "
        "run `pytest projects/ -q` (everything must be green), then open the first "
        "project whose next phase is ⬜ and continue from its `STEPS.md`.",
        "",
        f"## Overall: {pct}%  `{bar}`  ({done}/{total} phase-slots done)",
        "",
        "Legend: ✅ done · 🔧 in progress · ⬜ todo",
        "",
        "## Master matrix — all 11 cores × 6 phases",
        "",
        "| # | Project | Domain | P0 Golden | P1 pymodel | P2 RTL | P3 Synth | P4 P&R | P5 Signoff | % | Tracking |",
        "|:-:|---------|--------|:---------:|:----------:|:------:|:--------:|:------:|:----------:|:-:|----------|",
    ]
    order = sorted(M.PROJECTS, key=lambda p: p["num"])
    for p in order:
        cells = phase_cells(p)
        track = (f"[steps](projects/{p['key']}/STEPS.md) · "
                 f"[chk](projects/{p['key']}/CHECKPOINTS.md) · "
                 f"[tests](projects/{p['key']}/TESTS.md)")
        lines.append(f"| {p['num']} | **{p['name']}** | {p['domain']} | {cells} | "
                     f"{project_progress_pct(p)}% | {track} |")
    lines += [
        "",
        "## What 'done' means today",
        "",
        "Every project's **Phase 0 (golden reference)** and **Phase 1 (pymodel)** are "
        "implemented in pure Python and covered by passing pytest. These are RAM-trivial "
        "(<0.5 GB) and run on any laptop. **Phases 2–5 (RTL → GDSII)** are the RAM-heavy "
        "part and are not started — see RAM budget below.",
        "",
        "## RAM budget for the remaining phases (the OOM risk)",
        "",
        "Phase 0/1 (current) never OOMs. The wall is Phase 4 detailed routing, anchored to "
        "the real PtahCore data point (2.27 mm² flat ≈ 14 GB).",
        "",
        "| Project | Area | Flat synth | Flat GDSII peak | 16 GB laptop? | Strategy |",
        "|---------|------|:----------:|:---------------:|:-------------:|----------|",
        "| AnubisCore | 0.05 mm² | ~1 GB | ~1.5 GB | ✅ | flat |",
        "| SobekCore | 0.08 mm² | ~1 GB | ~2 GB | ✅ | flat |",
        "| HapiCore | 0.1 mm² | ~1 GB | ~2 GB | ✅ | flat |",
        "| SethCore | 0.1 mm² | ~1 GB | ~2 GB | ✅ | flat |",
        "| NeithCore | 0.3 mm² | ~2 GB | ~3–4 GB | ✅ | flat |",
        "| AtumCore | 0.5 mm² | ~2–3 GB | ~5–6 GB | ✅ | flat |",
        "| ImentetCore | 1.5 mm² | ~6–8 GB | ~9–11 GB | ⚠️ | tile-abut |",
        "| BastCore | 2.0 mm² | ~8–10 GB | ~12–14 GB | ⚠️ | tile-abut |",
        "| GebCore | 2.0 mm² | ~8–10 GB | ~12–14 GB | ⚠️ | tile-abut |",
        "| PtahConv | 3.0 mm² | ~12–16 GB | ~18–20 GB | ❌ flat | **must** tile-abut |",
        "| RaCore-Lite | 3.5 mm² | ~3–5 GB | ~3–5 GB | ✅ | hierarchical |",
        "| RaCore-Full | 16 mm² | — | needs ≥64 GB | ❌ | real iron |",
        "",
        "**Rule:** with tile-abutment everything except RaCore-Full closes on a 16 GB laptop.",
        "",
        "## Build / verify commands",
        "",
        "```bash",
        "pytest projects/ -q                 # all Phase 0/1 tests (fast, <0.5 GB)",
        "pytest projects/hapicore/tests -v   # one project",
        "python tools/gen_tracking.py        # regenerate this file + all tracking docs",
        "python tools/manifest.py            # (data only; edit to update status)",
        "```",
        "",
        "## Dependency build order (for Phases 2+)",
        "",
        "```",
        "HapiCore, AnubisCore           (no deps — build first)",
        "  → BastCore, SethCore         (need HapiCore)",
        "    → PtahConv, GebCore        (need BastCore)",
        "      → ImentetCore            (needs PtahConv + GebCore)",
        "SobekCore, NeithCore           (independent)",
        "AtumCore                       (needs SethCore + HapiCore)",
        "  → RaCore (capstone)          (needs ALL, KAI-conformant)",
        "```",
        "",
        "## Per-project resume index",
        "",
    ]
    for p in order:
        lines.append(f"- **{p['name']}** ({p['domain']}) — "
                     f"[STEPS](projects/{p['key']}/STEPS.md) · "
                     f"[CHECKPOINTS](projects/{p['key']}/CHECKPOINTS.md) · "
                     f"[TESTS](projects/{p['key']}/TESTS.md) · "
                     f"[spec]({p['doc']})")
    lines += ["",
              "---",
              "See [ROADMAP.md](ROADMAP.md) for the phased execution plan and "
              "[README.md](README.md) for the architecture overview.",
              ""]
    return "\n".join(lines)


def main():
    written = []
    for p in M.PROJECTS:
        written.append(w(f"projects/{p['key']}/STEPS.md", gen_steps(p)))
        written.append(w(f"projects/{p['key']}/CHECKPOINTS.md", gen_checkpoints(p)))
        written.append(w(f"projects/{p['key']}/TESTS.md", gen_tests(p)))
    written.append(w("PROGRESS.md", gen_progress()))
    print(f"Generated {len(written)} files:")
    for path in written:
        print("  " + path)


if __name__ == "__main__":
    main()
